### ISSUE TITLE
History reports being submitted without a pacer_docket_id value

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#270]
When this happens, it throws a big error because we need that ID. I can't reproduce this. Tried on both Firefox and Chrome and things looked fine. 

It's happening many times daily and needs fixing. Here's the error from CourtListener:

```
Task cl.recap.tasks.process_recap_docket_history_report with id 5411a36f-8581-4570-9d45-69dcd27fe0ac raised exception:
'ValidationError([u"\'pacer_case_id\' cannot be Null or empty in RECAP documents."])'


Task was called with args: (2131380,) kwargs: {}.

The contents of the full traceback was:

Traceback (most recent call last):
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/courtlistener/cl/recap/tasks.py", line 1371, in process_recap_docket_history_report
    d.save()
  File "/var/www/courtlistener/cl/search/models.py", line 562, in save
    "RECAP documents." % field)
ValidationError: [u"'pacer_case_id' cannot be Null or empty in RECAP documents."]
```

If we can reproduce it, I expect it'll be easy to fix.

**Comment by s-zeid** [comment]
Could this be related to #249 (which I just reproduced client-side)?

**Comment by mlissner** [comment]
The example you provided in #249 seems to have the pacer_case_id value, doesn't it?
